version: '3.7'
services:
  database:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - /db-data:/var/lib/postgresql
volumes:
  db-data:
